#image: 'proboci/ubuntu-14.04-lamp-beta'
steps:
  - name: Provision Drupal
    plugin: Drupal
    runInstall: standard
    settingsRequireFile: 'site-settings.php'
    settingsAppend: |
  $bar = 'baz';
  $foo = 'stuff';
