#image: 'proboci/ubuntu-14.04-lamp-beta'
assets:
  - testing
steps:
  - name: Provision Drupal
    plugin: Drupal
    runInstall: standard
  - name: Asset contents
    command: 'cat $ASSET_DIR/testing'

