image: php7_flat
allowAccessWhileBuilding: true
steps:
  - name: Sleep and setup a docroot
    plugin: Script
    script: |
      mkdir -p /var/www/html
      echo '<?php print phpinfo();' > /var/www/html/index.php 
      chmod 777 -R /var/www
notifications:
  webhook: http://localhost:6666
